services:
  php:
    container_name: "salt-lite-phpstan-php"
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    volumes:
      - ${SOURCE_DIR:-./}:/app
      - ./php-development.ini:/usr/local/etc/php/conf.d/settings.ini
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cli" # Used by PhpStorm for path mapping
      COMPOSER_AUTH: "{\"github-oauth\": {\"github.com\":\"${GITHUB_TOKEN}\"}}"
    extra_hosts:
      - host.docker.internal:host-gateway